telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\Home-pron\AppData\Local\Programs\Python\Python35\lib\site-packages\telegram\ext\dispatcher.py", line 265, in process_update
    handler.handle_update(update, self)
  File "C:\Users\Home-pron\AppData\Local\Programs\Python\Python35\lib\site-packages\telegram\ext\messagehandler.py", line 124, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 14, in talk_to_me
    print(user_text)
  File "C:\Users\Home-pron\AppData\Local\Programs\Python\Python35\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-5: character maps to <undefined>
